### ISSUE TITLE
数字证书生成报错

### ISSUE THREAD

**Issue by Newspiral** [Newspiral/newspiral-business#1]
使用管理平台EasySpiral生成数字证书时，报错提示“无法连接颁发证书的权威CA机构”，请问是何原因？

**Comment by yangzejie000** [comment]
有没有可能提供一键部署，比如使用shell或者docker-compose方式部署？环境的要求有说明文档吗？

**Comment by yangzejie000** [comment]
部署是否对openssl版本有特定要求，环境部署openssl后，运行过程中报ALPN unsupported，请问如何解决，是否需要额外安装openssl devel开发包？

**Comment by yangzejie000** [comment]
部署是否对openssl版本有特定要求，环境部署openssl后，运行过程中报ALPN unsupported，请问如何解决，是否需要额外安装openssl devel开发包？

**Comment by Newspiral** [comment]
管理平台申请证书分两种方式，其一，使用平台本身颁发的证书，技术上是自签名证书，不依赖外部CA；其二，使用外部权威CA在线颁发证书，这需要准备好对应的CA服务，并且修改区块链管理平台的配置项。
