### ISSUE TITLE
通道有无划分，比如类似fabric将通道划分为系统通道和应用通道？

### ISSUE THREAD

**Issue by SouthLion** [Newspiral/newspiral-business#13]

**Comment by Newspiral** [comment]
无，Newspiral的通道之间是完全独立的关系，因此不存在高于其他的系统通道。
每个通道内的合约可分为系统合约和业务合约，系统合约需要更高的通道权限方可调用。
PS：Fabric的这个系统通道的设计，跟它的存在排序服务这种超然角色节点的架构是有关系的，我们审慎的认为，这个是一个不太正确的架构选择。
